---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/yellenii/concourse.git
      branch: main
  - name: timer
    type: time
    source:
      interval: 1m

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-tutorial
      - get: timer
        trigger: true
      - task: hello-world
        file: resource-tutorial/resource.yml
        #        config:
        #          platform: linux
        #          inputs:
        #            - name: resource-tutorial
        #          run:
        #              path: echo
        #              args: ["hello world"]
              # path: sh
              #args: ["./resource-tutorial/web-task.sh"]
                #  inputs:
           
             # - name: resource-tutorial
        #        config:
        #        platform: linux
        #        image_resource:
        #          type: docker-image
        #          source: {repository: busybox}
        #        
        #        inputs: resource-tutorial
        #        
        #        run:
        #          path: resource-tutorial/web-task.sh
        #          
        ##file: resource-tutorial/resource.yml
