---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/yellenii/concourse.git
      branch: main
  - name: timer
    type: time
    source:
      interval: 1m

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-tutorial
      - get: timer
        trigger: true
      - task: hello-world
        file: resource-tutorial/resource.yml
